"""empty message

Revision ID: e8e97e215a06
Revises: 
Create Date: 2021-01-05 07:27:38.688318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e97e215a06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=60), nullable=True),
    sa.Column('company_address', sa.String(length=200), nullable=True),
    sa.Column('company_email', sa.String(length=120), nullable=True),
    sa.Column('contact_number', sa.String(length=120), nullable=True),
    sa.Column('nature', sa.String(length=120), nullable=True),
    sa.Column('logo_image', sa.String(length=30), nullable=True),
    sa.Column('expat_id', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_index(op.f('ix_companies_company_email'), 'companies', ['company_email'], unique=True)
    op.create_index(op.f('ix_companies_contact_number'), 'companies', ['contact_number'], unique=True)
    op.create_index(op.f('ix_companies_expat_id'), 'companies', ['expat_id'], unique=False)
    op.create_index(op.f('ix_companies_nature'), 'companies', ['nature'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('expat_id', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_expat_id'), 'departments', ['expat_id'], unique=False)
    op.create_table('leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(length=60), nullable=True),
    sa.Column('Description', sa.String(length=80), nullable=True),
    sa.Column('leave_date', sa.DateTime(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('expat_id', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaves_expat_id'), 'leaves', ['expat_id'], unique=False)
    op.create_table('renewcerpacs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cerpac_issue_date', sa.DateTime(), nullable=True),
    sa.Column('cerpac_exp_date', sa.DateTime(), nullable=True),
    sa.Column('cerpac_reference', sa.String(length=60), nullable=True),
    sa.Column('expat_id', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renewcerpacs_expat_id'), 'renewcerpacs', ['expat_id'], unique=False)
    op.create_table('renewpassport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passport_issue_date', sa.DateTime(), nullable=True),
    sa.Column('passport_exp_date', sa.DateTime(), nullable=True),
    sa.Column('expat_id', sa.String(length=16), nullable=True),
    sa.Column('is_passport_renewed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renewpassport_expat_id'), 'renewpassport', ['expat_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('expat_id', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_expat_id'), 'roles', ['expat_id'], unique=False)
    op.create_table('token_serials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('laps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_serial_id', sa.Integer(), nullable=True),
    sa.Column('runner_name', sa.String(length=100), nullable=True),
    sa.Column('expat_id', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['token_serial_id'], ['token_serials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laps_expat_id'), 'laps', ['expat_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('phone_number', sa.String(length=16), nullable=True),
    sa.Column('gender', sa.String(length=60), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=20), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('date_of_employment', sa.DateTime(), nullable=True),
    sa.Column('passport_pic', sa.String(length=50), nullable=True),
    sa.Column('employee_id', sa.String(length=16), nullable=True),
    sa.Column('lap_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('is_notified', sa.Boolean(), nullable=True),
    sa.Column('expat_id', sa.String(length=16), nullable=True),
    sa.Column('employment_age', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['lap_id'], ['laps.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_address'), 'employees', ['address'], unique=False)
    op.create_index(op.f('ix_employees_city'), 'employees', ['city'], unique=False)
    op.create_index(op.f('ix_employees_country'), 'employees', ['country'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employees_expat_id'), 'employees', ['expat_id'], unique=False)
    op.create_index(op.f('ix_employees_first_name'), 'employees', ['first_name'], unique=False)
    op.create_index(op.f('ix_employees_gender'), 'employees', ['gender'], unique=False)
    op.create_index(op.f('ix_employees_last_name'), 'employees', ['last_name'], unique=False)
    op.create_index(op.f('ix_employees_phone_number'), 'employees', ['phone_number'], unique=False)
    op.create_index(op.f('ix_employees_state'), 'employees', ['state'], unique=False)
    op.create_table('quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_of_positions', sa.Integer(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('quota_exp_date', sa.DateTime(), nullable=True),
    sa.Column('quota_upload', sa.String(length=30), nullable=True),
    sa.Column('quota_reference', sa.String(length=60), nullable=True),
    sa.Column('process_status', sa.Boolean(), nullable=True),
    sa.Column('expat_id', sa.String(length=16), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('lap_id', sa.Integer(), nullable=True),
    sa.Column('token_serial_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lap_id'], ['laps.id'], ),
    sa.ForeignKeyConstraint(['token_serial_id'], ['token_serials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quota_reference')
    )
    op.create_index(op.f('ix_quotas_expat_id'), 'quotas', ['expat_id'], unique=False)
    op.create_table('cerpacs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cerpac_issue_date', sa.DateTime(), nullable=True),
    sa.Column('expired_date', sa.DateTime(), nullable=True),
    sa.Column('cerpac_serial_no', sa.String(length=60), nullable=True),
    sa.Column('cerpac_upload', sa.String(length=20), nullable=True),
    sa.Column('process_status', sa.Boolean(), nullable=True),
    sa.Column('expat_id', sa.String(length=16), nullable=True),
    sa.Column('renewcerpac_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['renewcerpac_id'], ['renewcerpacs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cerpacs_expat_id'), 'cerpacs', ['expat_id'], unique=False)
    op.create_table('emergencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('relationship', sa.String(length=16), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('expat_id', sa.String(length=16), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_emergencies_expat_id'), 'emergencies', ['expat_id'], unique=False)
    op.create_index(op.f('ix_emergencies_phone'), 'emergencies', ['phone'], unique=False)
    op.create_index(op.f('ix_emergencies_relationship'), 'emergencies', ['relationship'], unique=False)
    op.create_table('passports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nationality', sa.String(length=60), nullable=True),
    sa.Column('passport_no', sa.String(length=16), nullable=True),
    sa.Column('process_status', sa.Boolean(), nullable=True),
    sa.Column('passport_exp_date', sa.DateTime(), nullable=True),
    sa.Column('passport_issue_date', sa.DateTime(), nullable=True),
    sa.Column('expat_id', sa.String(length=16), nullable=True),
    sa.Column('renewpassport_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['renewpassport_id'], ['renewpassport.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passport_no')
    )
    op.create_index(op.f('ix_passports_expat_id'), 'passports', ['expat_id'], unique=False)
    op.create_table('renewquota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quota_issue_date', sa.DateTime(), nullable=True),
    sa.Column('quota_exp_date', sa.DateTime(), nullable=True),
    sa.Column('quota_reference', sa.String(length=60), nullable=True),
    sa.Column('expat_id', sa.String(length=16), nullable=True),
    sa.Column('quota_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quota_id'], ['quotas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renewquota_expat_id'), 'renewquota', ['expat_id'], unique=False)
    op.create_table('renews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cerpac_id', sa.Integer(), nullable=True),
    sa.Column('quota_id', sa.Integer(), nullable=True),
    sa.Column('passport_id', sa.Integer(), nullable=True),
    sa.Column('new_issue_date', sa.DateTime(), nullable=True),
    sa.Column('new_expiry_date', sa.DateTime(), nullable=True),
    sa.Column('expat_id', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['cerpac_id'], ['cerpacs.id'], ),
    sa.ForeignKeyConstraint(['passport_id'], ['passports.id'], ),
    sa.ForeignKeyConstraint(['quota_id'], ['quotas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renews_expat_id'), 'renews', ['expat_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('renew_id', sa.Integer(), nullable=True),
    sa.Column('leave_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['leave_id'], ['leaves.id'], ),
    sa.ForeignKeyConstraint(['renew_id'], ['renews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approvals')
    op.drop_index(op.f('ix_renews_expat_id'), table_name='renews')
    op.drop_table('renews')
    op.drop_index(op.f('ix_renewquota_expat_id'), table_name='renewquota')
    op.drop_table('renewquota')
    op.drop_index(op.f('ix_passports_expat_id'), table_name='passports')
    op.drop_table('passports')
    op.drop_index(op.f('ix_emergencies_relationship'), table_name='emergencies')
    op.drop_index(op.f('ix_emergencies_phone'), table_name='emergencies')
    op.drop_index(op.f('ix_emergencies_expat_id'), table_name='emergencies')
    op.drop_table('emergencies')
    op.drop_index(op.f('ix_cerpacs_expat_id'), table_name='cerpacs')
    op.drop_table('cerpacs')
    op.drop_index(op.f('ix_quotas_expat_id'), table_name='quotas')
    op.drop_table('quotas')
    op.drop_index(op.f('ix_employees_state'), table_name='employees')
    op.drop_index(op.f('ix_employees_phone_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_last_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_gender'), table_name='employees')
    op.drop_index(op.f('ix_employees_first_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_expat_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_country'), table_name='employees')
    op.drop_index(op.f('ix_employees_city'), table_name='employees')
    op.drop_index(op.f('ix_employees_address'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_laps_expat_id'), table_name='laps')
    op.drop_table('laps')
    op.drop_table('users')
    op.drop_table('token_serials')
    op.drop_index(op.f('ix_roles_expat_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_renewpassport_expat_id'), table_name='renewpassport')
    op.drop_table('renewpassport')
    op.drop_index(op.f('ix_renewcerpacs_expat_id'), table_name='renewcerpacs')
    op.drop_table('renewcerpacs')
    op.drop_index(op.f('ix_leaves_expat_id'), table_name='leaves')
    op.drop_table('leaves')
    op.drop_index(op.f('ix_departments_expat_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_companies_nature'), table_name='companies')
    op.drop_index(op.f('ix_companies_expat_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_contact_number'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_email'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
